services:
  app:
    build: .
    expose:
      - "5000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:    
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

